name: CI/CD for NestJS App

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name:  Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build

  test:
    runs-on: [self-hosted, Windows, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name:  Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test

  deploy:
    runs-on: [self-hosted, Windows, x64]
    needs: build, test
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        run: npm run deploy
